### ISSUE TITLE
bids_face13 is not running

### ISSUE THREAD

**Issue by ShiangHu** [BUCANL/BIDS-Init-Face13-EEGLAB#2]
Hey @jadesjardins @Andesha,
I have these bugs: 
1. bids_export is not undefined
2. bids_face13
92  bids_export(data, 'targetdir', uigetdir, 'taskName', ...
Error using bids_export (line 197)
bids_format_eeglab error: undefined argument 'coordsys'

Error in bids_face13 (line 92)
bids_export(data, 'targetdir', uigetdir, 'taskName', ...

**Comment by Andesha** [comment]
Hi there,

I have some questions about your setup:

1. Are you attempting to initialize the Face13 data? Are the coordinate files inside of `sourcedata/misc/`?
2. Can you check that the following file exists at the given path: `Face13/code/BIDS-Init-Face13-EEGLAB/eeglab/plugins/bids-matlab-tools/bids_export.m`

Thank you!

**Comment by ShiangHu** [comment]
Yes. Before getting the LOSSLESS running, we need to covert the Face13 into BIDS. 
In sourcedata/misc/, I do have BioSemi_BUCANL_EEGLAB.sfp, standard_1005.elc, and standard_vol_SCCN.mat. Bids_export.m is there. 
After I downloaded the latest codes, now it works but warns with: 
Warning SOPEN (EDF): One block exceeds 61440 bytes.
Warning SOPEN (EDF-Write): relative scaling error is 6.852881e-05 (due to roundoff in PhysMax/Min)
I think it is ok now. Thank you.

**Comment by Andesha** [comment]
Hi,

Those warnings are standard and come as a result of rounding errors only. It should not have any negative effects.

Glad it works! Please do not hesitate to open another issue or email me (tk11br@brocku.ca) directly.

Thanks!
